// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class ALMACEN
{
    public string CODALMACEN { get; set; }

    public string NOMBREALMACEN { get; set; }

    public string POBLACION { get; set; }

    public string PROVINCIA { get; set; }

    public string NOTAS { get; set; }

    public string N { get; set; }

    public string CENTROCOSTE { get; set; }

    public double? STOCKMINIMO { get; set; }

    public double? STOCKMAXIMO { get; set; }

    public double? FACTOR { get; set; }

    public string DIRECCION { get; set; }

    public string TELEFONO { get; set; }

    public string FAX { get; set; }

    public string SERIETRASPASOS { get; set; }

    public int? CODEMPRESACONTABLE { get; set; }

    public int? VALORACIONTRASPASOS { get; set; }

    public int? VALORACIONINVENTARIO { get; set; }

    public int? PVPETIQUETAS { get; set; }

    public string POPERACIONAL { get; set; }

    public int? CODCLIENTE { get; set; }

    public DateTime? FECHAULTREP { get; set; }

    public byte[] VERSION { get; set; }

    public DateTime? ULTFACTURACIONPRESTAMOS { get; set; }

    public DateTime? FECHABLOQUEO { get; set; }

    public int? VALORACIONCONSUMOS { get; set; }

    public int? VALORACIONTRASPASOSDMN { get; set; }

    public int? VALORACIONINVENTARIOSDMN { get; set; }

    public bool? ESMERMAS { get; set; }

    public bool ESPLANIFICACION { get; set; }

    public string EMAIL { get; set; }

    public DateTime HORACAMBIOTURNO { get; set; }

    public string CODPOSTAL { get; set; }

    public string CODPAIS { get; set; }

    public string SERIETRASPASOSTRANPORTE { get; set; }
}