// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class ARTICULOS
{
    public int CODARTICULO { get; set; }

    public string DESCRIPCION { get; set; }

    public string DESCRIPADIC { get; set; }

    public int? TIPOIMPUESTO { get; set; }

    public short? DPTO { get; set; }

    public short? SECCION { get; set; }

    public short? FAMILIA { get; set; }

    public short? SUBFAMILIA { get; set; }

    public short? LINEA { get; set; }

    public string TEMPORADA { get; set; }

    public string GENERARETIQ { get; set; }

    public byte[] FOTO { get; set; }

    public int? MARCA { get; set; }

    public string CODTALLA { get; set; }

    public string NORMA { get; set; }

    public string TACON { get; set; }

    public string COMPOSICION { get; set; }

    public string ARTICULOVIRTUAL { get; set; }

    public string TIENETC { get; set; }

    public double? UNID1C { get; set; }

    public double? UNID2C { get; set; }

    public double? UNID3C { get; set; }

    public double? UNID4C { get; set; }

    public double? UNID1V { get; set; }

    public double? UNID2V { get; set; }

    public double? UNID3V { get; set; }

    public double? UNID4V { get; set; }

    public string ESKIT { get; set; }

    public string USARNUMSERIE { get; set; }

    public string GENNUMSERIE { get; set; }

    public int? TIPO { get; set; }

    public DateTime? FECHAMODIFICADO { get; set; }

    public string REFPROVEEDOR { get; set; }

    public string CONTRAPARTIDAVENTA { get; set; }

    public string CONTRAPARTIDACOMPRA { get; set; }

    public string UNIDADMEDIDA { get; set; }

    public double? UDSELABORACION { get; set; }

    public double? MEDIDAREFERENCIA { get; set; }

    public string PORPESO { get; set; }

    public string USASTOCKS { get; set; }

    public int? IMPUESTOCOMPRA { get; set; }

    public string DESCATALOGADO { get; set; }

    public double? UDSTRASPASO { get; set; }

    public string TIPOARTICULO { get; set; }

    public string GARANTIACOMPRA { get; set; }

    public string GARANTIAVENTA { get; set; }

    public int? COLORFONDO { get; set; }

    public int? COLORTEXTO { get; set; }

    public string TIPOSAT { get; set; }

    public DateTime? FACTPORHORA { get; set; }

    public int? CONSUMADIC { get; set; }

    public double? MARGEN { get; set; }

    public double? CARGO1 { get; set; }

    public double? CARGO2 { get; set; }

    public int? NUMCONSUMICIONES { get; set; }

    public int? CODCENTRAL { get; set; }

    public string CONTRAPARTIDACOSTEVENTAS { get; set; }

    public int? CODDISENY { get; set; }

    public int? CODIGOADUANA { get; set; }

    public string MEDIDA2 { get; set; }

    public string VISIBLEWEB { get; set; }

    public int? DIASCADUCIDAD { get; set; }

    public double? PORCRETENCION { get; set; }

    public string CONTRAPARTIDACONSUMO { get; set; }

    public string CONTRAPARTIDAVENTADMN { get; set; }

    public string CONTRAPARTIDACOMPRADMN { get; set; }

    public string CONTRAPARTIDACOSTEVENTASDMN { get; set; }

    public bool? DESCARGADO { get; set; }

    public double? PRECIOMINIMO { get; set; }

    public double? PRECIOMAXIMO { get; set; }

    public string PRECIOLIBRE { get; set; }

    public bool? HIOPOS_IMPRIMIRCOCINA { get; set; }

    public bool? HIOPOS_EBT { get; set; }

    public int? HIOPOS_TAKEAWAY { get; set; }

    public string AVISOVENTA { get; set; }

    public byte[] FOTOSHA { get; set; }

    public bool? FORZARUDSENTERASVENTA { get; set; }

    public int? DURACION { get; set; }

    public int? IDTALONARIO { get; set; }

    public bool? HIOPOS_IMPRIMIRCOCINA2 { get; set; }

    public bool? HIOPOS_IMPRIMIRCOCINA3 { get; set; }

    public bool? HIOPOS_ISMODIFICADOR { get; set; }

    public bool? NODTOAPLICABLE { get; set; }

    public string CONTRAPARTIDADEVOLCOMPRA { get; set; }

    public string CONTRAPARTIDADEVOLVENTA { get; set; }

    public string CONTRAPARTIDADEVOLCOSTEVENTA { get; set; }

    public string CONTRAPARTIDADEVOLCOMPRADMN { get; set; }

    public string CONTRAPARTIDADEVOLVENTADMN { get; set; }

    public string CONTRAPARTIDADEVOLCOSTEVENTASDM { get; set; }

    public int? REGIMRET_IVA { get; set; }

    public int? REGIMRET_BASEIMPONIBLE { get; set; }

    public string SOLICITARCOMENTARIO { get; set; }

    public string DIRCONTAB { get; set; }

    public int? SUBEMPRESA { get; set; }

    public string CONTRAPARTIDAVENTAEXONERADA { get; set; }

    public string CONTRAPARTIDADEVOLVENTAEXONERADA { get; set; }

    public string CONTRAPARTIDAFALTANTESINVENTARIO { get; set; }

    public string CONTRAPARTIDASOBRANTESINVENTARIO { get; set; }

    public string CONTRAPARTIDAORDENESFAB { get; set; }

    public string FIJARPV_CADADIA { get; set; }

    public string FIJARPV_ALCAMBIARPRECIO { get; set; }

    public int? FORMADEPESO { get; set; }

    public string CONTRAPARTIDACONSUMOS { get; set; }

    public string USARFID { get; set; }

    public string TIPOPRODSAFT { get; set; }

    public byte[] VERSION { get; set; }
}