// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class DEPARTAMENTO
{
    public int NUMDPTO { get; set; }

    public string DESCRIPCION { get; set; }

    public byte[] IMAGEN { get; set; }

    public byte[] VERSION { get; set; }

    public string CENTROCOSTE { get; set; }

    public bool? ROUTINGHOTEL { get; set; }

    public string VISIBLEWEB { get; set; }
}