// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class FORMATOSARTICULOS
{
    public int CODARTICULO { get; set; }

    public int CODFORMATO { get; set; }

    public string CODBARRAS { get; set; }

    public string COMPRA { get; set; }

    public string VENTA { get; set; }

    public string VISIBLEENVENTA { get; set; }

    public string VISIBLEENCOMPRA { get; set; }
}