// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MvcWebPage.MLAVID;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MvcWebPage.MLAVID
{
    public partial interface IMLAVIDContextProcedures
    {
        Task<List<IT_ART_PROVResult>> IT_ART_PROVAsync(string REFERENCIA, string CODALMACEN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_DEPARTAMENTOResult>> IT_DEPARTAMENTOAsync(string CODALMACEN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_DETALLESINVResult>> IT_DETALLESINVAsync(string OD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_LOGINResult>> IT_LOGINAsync(string USUARIO, string PASSWORD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_PEDIDOSResult>> IT_PEDIDOSAsync(string CODALMACEN, short? DPTO, int? year, int? month, int? day, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_PEDIDOS_AUTResult>> IT_PEDIDOS_AUTAsync(string CODALMACEN, string NOMPROVEEDOR, int? year1, int? month1, int? day1, int? year2, int? month2, int? day2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_PEDIDOS_AUT_DETResult>> IT_PEDIDOS_AUT_DETAsync(int? ID_CAB, string NUMSERIE, int? NUMPEDIDO, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_PEDIDOS_AUTPResult>> IT_PEDIDOS_AUTPAsync(string CODALMACEN, int? IDESTADO, int? year1, int? month1, int? day1, int? year2, int? month2, int? day2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_PEDIDOS_CAB2Result>> IT_PEDIDOS_CAB2Async(string CODALMACEN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_SELECCIONAR_ARTICULOSResult>> IT_SELECCIONAR_ARTICULOSAsync(string IT_ART, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_SELECT_MODResult>> IT_SELECT_MODAsync(string CODALMACEN, short? DPTO, int? year, int? month, int? day, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<IT_USUARIOSResult>> IT_USUARIOSAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
