// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IMPUESTOS
{
    public int TIPOIVA { get; set; }

    public string DESCRIPCION { get; set; }

    public double? IVA { get; set; }

    public double? REQ { get; set; }

    public double? CUOTA { get; set; }

    public string CUENTAIVAREP { get; set; }

    public string CUENTAIVASOP { get; set; }

    public string CUENTARECREP { get; set; }

    public string CUENTARECSOP { get; set; }

    public int? APLICACIONTASA2 { get; set; }

    public int? TIPOIVARELACIONADO { get; set; }

    public byte[] VERSION { get; set; }

    public string CODIGOIMPUESTO { get; set; }

    public DateTime? FUTURODESDE1 { get; set; }

    public double? FUTUROIVA1 { get; set; }

    public double? FUTUROREQ1 { get; set; }

    public DateTime? FUTURODESDE2 { get; set; }

    public double? FUTUROIVA2 { get; set; }

    public double? FUTUROREQ2 { get; set; }

    public string CUENTAIVASOPDEVOL { get; set; }

    public string CUENTAIVAREPDEVOL { get; set; }

    public string MOTEXENCION { get; set; }

    public int? TIPO_IMPUESTO_AENA { get; set; }

    public string DESC_TIPO_IMPUESTO_AENA { get; set; }

    public int? CODGRUPO { get; set; }

    public string ESPACIOFISCAL { get; set; }

    public int? TIPO_COMPROBANTEDIARIO { get; set; }
}