// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_ARTICULOS_PROVEEDOR
{
    public string REFERENCIA { get; set; }

    public int CODARTICULO { get; set; }

    public string DESCRIPCION { get; set; }

    public double? DOSIS { get; set; }

    public string UNIDADM { get; set; }

    public string UNIDADMD { get; set; }

    public string CODALMACEN { get; set; }

    public string PROVEEDOR_A { get; set; }

    public double? PORCENTAJE_A { get; set; }

    public double? PRECIO_A { get; set; }

    public string CODIGO_A { get; set; }

    public string PROVEEDOR_B { get; set; }

    public double? PORCENTAJE_B { get; set; }

    public double? PRECIO_B { get; set; }

    public string CODIGO_B { get; set; }

    public string PROVEEDOR_C { get; set; }

    public double? PORCENTAJE_C { get; set; }

    public double? PRECIO_C { get; set; }

    public string CODIGO_C { get; set; }

    public double? LEADTIME { get; set; }

    public double? STOCK_SEGURIDAD { get; set; }

    public double? STOCK_MAXIMO { get; set; }

    public double? FRECUENCIA { get; set; }
}