// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_DEPARTAMENTOResult
    {
        public int NUMDPTO { get; set; }
        public short? DPTO { get; set; }
        public string DESCRIPCION { get; set; }
        public int? MODIFICADO { get; set; }
        public int? ESTATUS { get; set; }
    }
}
