// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_DETALLESINVResult
    {
        public DateTime FECHA { get; set; }
        public string CODALMACEN { get; set; }
        public int? TIPOVALORACION { get; set; }
        public string SERIE { get; set; }
        public int? NUMERO { get; set; }
        public int? CODVENDEDOR { get; set; }
        public string COMPLETO { get; set; }
        public int? METODO { get; set; }
        public string INICIAL { get; set; }
        public string BLOQUEADO { get; set; }
        public int? TIPOVALORACIONDMN { get; set; }
        public short ESTADO { get; set; }
        public bool? ESCIERRE { get; set; }
        public short? ENLACE_EJERCICIO { get; set; }
        public short? ENLACE_EMPRESA { get; set; }
        public string ENLACE_USUARIO { get; set; }
        public int? ENLACE_ASIENTO { get; set; }
        public bool? VIENEDEHIOFFICE { get; set; }
    }
}
