// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_INV_MENSUALES_CAB
{
    public int ID { get; set; }

    public DateTime? FECHA { get; set; }

    public TimeSpan? HORA { get; set; }

    public int? ESTATUS { get; set; }

    public string CODALMACEN { get; set; }

    public int? NUMDPTO { get; set; }

    public string _ALMACEN { get; set; }

    public string _DEPARTAMENTO { get; set; }

    public string _DETALLE { get; set; }

    public string _ESTATUS { get; set; }

    public string _REFERENCIA { get; set; }

    public virtual ICollection<IT_INV_MENSUALES_LIN> IT_INV_MENSUALES_LIN { get; set; } = new List<IT_INV_MENSUALES_LIN>();
}