// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_PEDIDOS_AUTPResult
    {
        public int? CODPROVEEDOR { get; set; }
        public string DESCRIPCION { get; set; }
        public double? TOTNETO { get; set; }
        public double? TOTIMPUESTOS { get; set; }
        public double? TOTBRUTO { get; set; }
        public DateTime? FECHAPEDIDO { get; set; }
        public int? IDESTADO { get; set; }
        public string NO_FACTURA { get; set; }
        public string RES_VALIDACION { get; set; }
        public string DETALLE { get; set; }
        public string ORDEN_DE_COMPRA { get; set; }
        public string FACTURA_PROV { get; set; }
        public DateTime? ENTREGA_ESTIMADA { get; set; }
        public string ESTATUS { get; set; }
        public string NOMBREALMACEN { get; set; }
        public string NOMPROVEEDOR { get; set; }
        public string NUMSERIE { get; set; }
        public string CODALMACEN { get; set; }
        public int NUMPEDIDO { get; set; }
        public int ID { get; set; }
        public int? ID_ORDEN { get; set; }
    }
}
