// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_PERFILES
{
    public string descripcion { get; set; }

    public int tipoUsuario { get; set; }

    public bool PedLibre { get; set; }

    public bool PedModifica { get; set; }

    public bool PedElimina { get; set; }

    public bool AccesoP { get; set; }

    public bool AccesoI { get; set; }

    public bool InvModifica { get; set; }

    public bool InvElimina { get; set; }

    public bool AccesoConfig { get; set; }

    public bool AccesoV { get; set; }

    public bool AccesoP1 { get; set; }
}