// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_PEDIDOS_NUMPEDIDOS_LIN
{
    public int ID_CAB { get; set; }

    public string NUMSERIE { get; set; }

    public string CODALMACEN { get; set; }

    public int NUMPEDIDO { get; set; }

    public int NUMLINEA { get; set; }

    public int? CODARTICULO { get; set; }

    public string REFERENCIA { get; set; }

    public string REFERENCIA2 { get; set; }

    public int? CODPROVEEDOR { get; set; }

    public double? PORCENTAJE { get; set; }

    public double? CANTIDAD { get; set; }

    public double? PRECIO { get; set; }

    public double? SUGERIDO { get; set; }

    public int? SEMAFORO { get; set; }

    public string CODIGO { get; set; }

    public int? CODFORMATO { get; set; }

    public short? TIPOIMPUESTO { get; set; }

    public double? IVA { get; set; }

    public double? REQ { get; set; }

    public virtual IT_PEDIDOS_NUMPEDIDOS_CAB IT_PEDIDOS_NUMPEDIDOS_CAB { get; set; }
}