// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_PEDIDOS_NUMPEDIDOS_CAB
{
    public int ID { get; set; }

    public string NUMSERIE { get; set; }

    public string CODALMACEN { get; set; }

    public int NUMPEDIDO { get; set; }

    public DateTime? FECHAPEDIDO { get; set; }

    public int? NUMDPTO { get; set; }

    public int? CODVENDEDOR { get; set; }

    public int? ID_ORDEN { get; set; }

    public virtual ICollection<IT_PEDIDOS_NUMPEDIDOS_LIN> IT_PEDIDOS_NUMPEDIDOS_LIN { get; set; } = new List<IT_PEDIDOS_NUMPEDIDOS_LIN>();
}