// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_PEDIDOS_CAB
{
    public int ID { get; set; }

    public DateTime? FECHA { get; set; }

    public TimeSpan? HORA { get; set; }

    public int? ESTATUS { get; set; }

    public string CODALMACEN { get; set; }

    public int? NUMDPTO { get; set; }

    public int? MODIFICADO { get; set; }

    public int? CODVENDEDOR { get; set; }

    public virtual ICollection<IT_PEDIDOS_LIN> IT_PEDIDOS_LIN { get; set; } = new List<IT_PEDIDOS_LIN>();
}