// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_PEDIDOS_AUT_DETResult
    {
        public double? UNIDADESTOTAL { get; set; }
        public double? UNIDADESPEN { get; set; }
        public string UNIDADMD { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESCRIPCION2 { get; set; }
        public double? PRECIO { get; set; }
        public double? DTO { get; set; }
        public double? TOTALLINEA { get; set; }
        public double? TOTAL { get; set; }
        public string CODIGO { get; set; }
        public string REFERENCIA { get; set; }
        public string REFERENCIA2 { get; set; }
        public int? CODARTICULO { get; set; }
        public int? CODPROVEEDOR { get; set; }
        public double? PORCENTAJE { get; set; }
        public double? CANTIDAD { get; set; }
        public double? SUGERIDO { get; set; }
        public int? SEMAFORO { get; set; }
        public int? CODFORMATO { get; set; }
        public int NUMLINEA { get; set; }
        public short? TIPOIMPUESTO { get; set; }
        public double? IVA { get; set; }
        public double? REQ { get; set; }
        public int? COLOR { get; set; }
        public double? TOTREQ { get; set; }
        public double? TOTIVA { get; set; }
    }
}
