// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_PEDIDOS_CAB2Result
    {
        public int ID { get; set; }
        public DateTime? FECHA { get; set; }
        public TimeSpan? HORA { get; set; }
        public int? ESTATUS { get; set; }
        public string CODALMACEN { get; set; }
        public string SUCURSAL { get; set; }
        public int? NUMDPTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public int? MODIFICADO { get; set; }
        public string ESTATUS2 { get; set; }
        public string DETALLE { get; set; }
        public string REFERENCIA { get; set; }
    }
}
