// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class IT_PEDIDOS_LIN
{
    public int ID_CAB { get; set; }

    public string CODALMACEN { get; set; }

    public int CODARTICULO { get; set; }

    public string REFERENCIA { get; set; }

    public double? CANTIDAD { get; set; }

    public double? SUGERIDO { get; set; }

    public int? SEMAFORO { get; set; }

    public int? CODFORMATO { get; set; }

    public virtual IT_PEDIDOS_CAB ID_CABNavigation { get; set; }
}