// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_PEDIDOSResult
    {
        public double? SUGERIDO { get; set; }
        public double? SUGERIDO3 { get; set; }
        public string MAXIMO_PEDIR_STR { get; set; }
        public int? COLOR_TMP { get; set; }
        public int? COLOR { get; set; }
        public double? CANTIDAD { get; set; }
        public double? CANTIDAD_PEDIDA { get; set; }
        public double? SUGERIDO2 { get; set; }
        public int CODARTICULO { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNIDADCOMPRA { get; set; }
        public double? MULTIPLOPEDIR { get; set; }
        public double? MAXIMO_PEDIR { get; set; }
        public double? EXISTENCIA_ACTUAL { get; set; }
        public int? CODFORMATO { get; set; }
    }
}
