// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_SELECT_MODResult
    {
        public int CODARTICULO { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNIDADMEDIDA { get; set; }
        public double? MULTIPLOPEDIR { get; set; }
        public double? MAXIMO_PEDIR { get; set; }
        public double? EXISTENCIA_ACTUAL { get; set; }
        public int? CANTIDAD { get; set; }
    }
}
