// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWebPage.MLAVID
{
    public partial class IT_SELECCIONAR_ARTICULOSResult
    {
        public string REFPROVEEDOR { get; set; }
        public int CODARTICULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNIDADCOMPRA { get; set; }
        public double? MULTIPLOPEDIR { get; set; }
        public double? MAXIMO_PEDIR { get; set; }
        public double? EXISTENCIA_ACTUAL { get; set; }
        public double? PRECIO_A { get; set; }
        public string DESCRIPCION_DEPTO { get; set; }
        public double? UNIDADES_EXISTENCIA { get; set; }
    }
}
