// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MvcWebPage.MLAVID;

public partial class MLAVIDContext : DbContext
{
    public MLAVIDContext(DbContextOptions<MLAVIDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ALMACEN> ALMACEN { get; set; }

    public virtual DbSet<ARTICULOS> ARTICULOS { get; set; }

    public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }

    public virtual DbSet<IMPUESTOS> IMPUESTOS { get; set; }

    public virtual DbSet<IT_ARTICULOS_PROVEEDOR> IT_ARTICULOS_PROVEEDOR { get; set; }

    public virtual DbSet<IT_INV_MENSUALES_CAB> IT_INV_MENSUALES_CAB { get; set; }

    public virtual DbSet<IT_INV_MENSUALES_LIN> IT_INV_MENSUALES_LIN { get; set; }

    public virtual DbSet<IT_PEDIDOS_CAB> IT_PEDIDOS_CAB { get; set; }

    public virtual DbSet<IT_PEDIDOS_LIN> IT_PEDIDOS_LIN { get; set; }

    public virtual DbSet<IT_PEDIDOS_NUMPEDIDOS_CAB> IT_PEDIDOS_NUMPEDIDOS_CAB { get; set; }

    public virtual DbSet<IT_PEDIDOS_NUMPEDIDOS_LIN> IT_PEDIDOS_NUMPEDIDOS_LIN { get; set; }

    public virtual DbSet<IT_PERFILES> IT_PERFILES { get; set; }

    public virtual DbSet<MONEDAS> MONEDAS { get; set; }

    public virtual DbSet<MOVIMENTS> MOVIMENTS { get; set; }

    public virtual DbSet<PEDCOMPRACAB> PEDCOMPRACAB { get; set; }

    public virtual DbSet<PEDCOMPRALIN> PEDCOMPRALIN { get; set; }

    public virtual DbSet<PEDCOMPRATOT> PEDCOMPRATOT { get; set; }

    public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }

    public virtual DbSet<REM_FRONTS> REM_FRONTS { get; set; }

    public virtual DbSet<SUCURSALES> SUCURSALES { get; set; }

    public virtual DbSet<VENDEDORES> VENDEDORES { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Modern_Spanish_CI_AS");

        modelBuilder.Entity<ALMACEN>(entity =>
        {
            entity.HasKey(e => e.CODALMACEN).HasName("ALMACEN_PK");

            entity.HasIndex(e => e.VERSION, "IDX_ALMACENVERSION");

            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CENTROCOSTE)
                .HasMaxLength(6)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODPAIS).HasMaxLength(2);
            entity.Property(e => e.CODPOSTAL).HasMaxLength(15);
            entity.Property(e => e.DIRECCION)
                .HasMaxLength(30)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.EMAIL).HasMaxLength(30);
            entity.Property(e => e.ESMERMAS).HasDefaultValueSql("((0))");
            entity.Property(e => e.FAX)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHABLOQUEO).HasColumnType("datetime");
            entity.Property(e => e.FECHAULTREP).HasColumnType("datetime");
            entity.Property(e => e.HORACAMBIOTURNO)
                .HasDefaultValueSql("((-2))")
                .HasColumnType("datetime");
            entity.Property(e => e.N)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.NOMBREALMACEN)
                .HasMaxLength(30)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NOTAS).HasColumnType("ntext");
            entity.Property(e => e.POBLACION)
                .HasMaxLength(30)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.POPERACIONAL)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PROVINCIA)
                .HasMaxLength(30)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SERIETRASPASOS)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SERIETRASPASOSTRANPORTE).HasMaxLength(4);
            entity.Property(e => e.TELEFONO)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ULTFACTURACIONPRESTAMOS).HasColumnType("datetime");
            entity.Property(e => e.VERSION)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<ARTICULOS>(entity =>
        {
            entity.HasKey(e => e.CODARTICULO).HasName("ARTICULOS_PK");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("ARTICULOS_CHANGE");
                    tb.HasTrigger("ARTICULOS_DELETE_HPC");
                    tb.HasTrigger("ARTICULOS_FOTOCHANGE");
                    tb.HasTrigger("ARTICULOS_FOTOINSERT");
                    tb.HasTrigger("ARTICULOS_INSERT");
                    tb.HasTrigger("ARTICULOS_INSERT_ARTICULOSESTADISTICA");
                    tb.HasTrigger("ARTICULOS_INSERT_CREARCAMPOSLIBRES");
                    tb.HasTrigger("ARTICULOS_INSERT_HIOPOS");
                    tb.HasTrigger("ARTICULOS_INSERT_SETMARCA");
                    tb.HasTrigger("VISIBLEWEB_UPDATED");
                });

            entity.HasIndex(e => e.CONSUMADIC, "ARTICULOS_CONSUMADIC");

            entity.HasIndex(e => e.CODARTICULO, "ARTICULOS_CONTRAPARTIDAS");

            entity.HasIndex(e => new { e.DPTO, e.SECCION }, "ARTICULOS_DPTO");

            entity.HasIndex(e => new { e.DPTO, e.SECCION, e.DESCRIPCION, e.REFPROVEEDOR, e.CODARTICULO }, "ARTICULOS_DPTO_SECC_DESC");

            entity.HasIndex(e => new { e.DPTO, e.SECCION, e.DESCRIPCION, e.CODARTICULO }, "ARTICULOS_DPTO_SECC_DESC_COD");

            entity.HasIndex(e => new { e.DPTO, e.SECCION, e.REFPROVEEDOR, e.CODARTICULO }, "ARTICULOS_DPTO_SECC_REF");

            entity.HasIndex(e => new { e.REFPROVEEDOR, e.CODARTICULO }, "ARTICULOS_REFERENCIA");

            entity.HasIndex(e => e.USARNUMSERIE, "ARTICULOS_USARNUMSERIE");

            entity.HasIndex(e => e.VERSION, "IDX_ARTICULOSVERSION");

            entity.Property(e => e.CODARTICULO).ValueGeneratedNever();
            entity.Property(e => e.ARTICULOVIRTUAL)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.AVISOVENTA)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODTALLA)
                .HasMaxLength(10)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.COMPOSICION)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDACOMPRA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDACOMPRADMN)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDACONSUMO)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDACONSUMOS)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDACOSTEVENTAS)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDACOSTEVENTASDMN)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLCOMPRA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLCOMPRADMN)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLCOSTEVENTA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLCOSTEVENTASDM)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLVENTA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLVENTADMN)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDADEVOLVENTAEXONERADA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDAFALTANTESINVENTARIO)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDAORDENESFAB)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDASOBRANTESINVENTARIO)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDAVENTA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDAVENTADMN)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CONTRAPARTIDAVENTAEXONERADA)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DESCARGADO).HasDefaultValueSql("((0))");
            entity.Property(e => e.DESCATALOGADO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.DESCRIPADIC)
                .HasMaxLength(25)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(40)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DIRCONTAB).HasMaxLength(8);
            entity.Property(e => e.DPTO).HasDefaultValueSql("((0))");
            entity.Property(e => e.ESKIT)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.FACTPORHORA).HasColumnType("datetime");
            entity.Property(e => e.FAMILIA).HasDefaultValueSql("((0))");
            entity.Property(e => e.FECHAMODIFICADO).HasColumnType("datetime");
            entity.Property(e => e.FIJARPV_ALCAMBIARPRECIO).HasMaxLength(1);
            entity.Property(e => e.FIJARPV_CADADIA).HasMaxLength(1);
            entity.Property(e => e.FOTO).HasColumnType("image");
            entity.Property(e => e.FOTOSHA).HasMaxLength(20);
            entity.Property(e => e.GARANTIACOMPRA)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.GARANTIAVENTA)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.GENERARETIQ)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.GENNUMSERIE)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.HIOPOS_IMPRIMIRCOCINA2).HasDefaultValueSql("((0))");
            entity.Property(e => e.HIOPOS_IMPRIMIRCOCINA3).HasDefaultValueSql("((0))");
            entity.Property(e => e.HIOPOS_ISMODIFICADOR).HasDefaultValueSql("((0))");
            entity.Property(e => e.LINEA).HasDefaultValueSql("((0))");
            entity.Property(e => e.MEDIDA2)
                .HasMaxLength(10)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.MEDIDAREFERENCIA).HasDefaultValueSql("((1))");
            entity.Property(e => e.NORMA)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PORPESO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.PRECIOLIBRE)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.REFPROVEEDOR)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SECCION).HasDefaultValueSql("((0))");
            entity.Property(e => e.SOLICITARCOMENTARIO).HasMaxLength(1);
            entity.Property(e => e.SUBFAMILIA).HasDefaultValueSql("((0))");
            entity.Property(e => e.TACON)
                .HasMaxLength(10)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TEMPORADA)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TIENETC)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.TIPOARTICULO)
                .HasMaxLength(1)
                .HasDefaultValueSql("('A')");
            entity.Property(e => e.TIPOPRODSAFT).HasMaxLength(1);
            entity.Property(e => e.TIPOSAT)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.UDSELABORACION).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID1C).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID1V).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID2C).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID2V).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID3C).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID3V).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID4C).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNID4V).HasDefaultValueSql("((1))");
            entity.Property(e => e.UNIDADMEDIDA)
                .HasMaxLength(10)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.USARFID).HasMaxLength(1);
            entity.Property(e => e.USARNUMSERIE)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.USASTOCKS)
                .HasMaxLength(1)
                .HasDefaultValueSql("('T')")
                .IsFixedLength();
            entity.Property(e => e.VERSION)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.VISIBLEWEB)
                .HasMaxLength(1)
                .IsFixedLength();
        });

        modelBuilder.Entity<DEPARTAMENTO>(entity =>
        {
            entity.HasKey(e => e.NUMDPTO).HasName("DEPARTAMENTO_PK");

            entity.ToTable(tb => tb.HasTrigger("DEPARTAMENTO_CHANGE"));

            entity.HasIndex(e => e.NUMDPTO, "IDX_DEPARTAMENTONUMDPTO");

            entity.HasIndex(e => e.VERSION, "IDX_DEPARTAMENTOVERSION");

            entity.Property(e => e.NUMDPTO).ValueGeneratedNever();
            entity.Property(e => e.CENTROCOSTE).HasMaxLength(6);
            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(25)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.IMAGEN).HasColumnType("image");
            entity.Property(e => e.VERSION)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.VISIBLEWEB).HasMaxLength(1);
        });

        modelBuilder.Entity<IMPUESTOS>(entity =>
        {
            entity.HasKey(e => e.TIPOIVA).HasName("IMPUESTOS_PK");

            entity.HasIndex(e => e.VERSION, "IDX_IMPUESTOSVERSION");

            entity.Property(e => e.TIPOIVA).ValueGeneratedNever();
            entity.Property(e => e.APLICACIONTASA2).HasDefaultValueSql("((2))");
            entity.Property(e => e.CODIGOIMPUESTO).HasMaxLength(10);
            entity.Property(e => e.CUENTAIVAREP)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CUENTAIVAREPDEVOL)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CUENTAIVASOP)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CUENTAIVASOPDEVOL)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CUENTARECREP)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CUENTARECSOP)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DESC_TIPO_IMPUESTO_AENA).HasMaxLength(30);
            entity.Property(e => e.ESPACIOFISCAL).HasMaxLength(10);
            entity.Property(e => e.FUTURODESDE1).HasColumnType("datetime");
            entity.Property(e => e.FUTURODESDE2).HasColumnType("datetime");
            entity.Property(e => e.MOTEXENCION).HasMaxLength(3);
            entity.Property(e => e.VERSION)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<IT_ARTICULOS_PROVEEDOR>(entity =>
        {
            entity.HasKey(e => new { e.CODALMACEN, e.REFERENCIA }).HasName("CODALMACEN_PK");

            entity.Property(e => e.CODALMACEN).HasMaxLength(3);
            entity.Property(e => e.CODIGO_A).HasMaxLength(50);
            entity.Property(e => e.CODIGO_B).HasMaxLength(50);
            entity.Property(e => e.CODIGO_C).HasMaxLength(50);
            entity.Property(e => e.DESCRIPCION).HasMaxLength(100);
            entity.Property(e => e.PROVEEDOR_A).HasMaxLength(20);
            entity.Property(e => e.PROVEEDOR_B).HasMaxLength(20);
            entity.Property(e => e.PROVEEDOR_C).HasMaxLength(20);
            entity.Property(e => e.REFERENCIA)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UNIDADM).HasMaxLength(15);
            entity.Property(e => e.UNIDADMD).HasMaxLength(50);
        });

        modelBuilder.Entity<IT_INV_MENSUALES_CAB>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_IT_INV_MENSUALES_CAB_ID");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CODALMACEN).HasMaxLength(3);
            entity.Property(e => e.FECHA).HasColumnType("date");
            entity.Property(e => e._ALMACEN).HasMaxLength(30);
            entity.Property(e => e._DEPARTAMENTO).HasMaxLength(25);
            entity.Property(e => e._DETALLE).HasMaxLength(100);
            entity.Property(e => e._ESTATUS).HasMaxLength(50);
            entity.Property(e => e._REFERENCIA)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<IT_INV_MENSUALES_LIN>(entity =>
        {
            entity.HasKey(e => new { e.ID, e.REFERENCIA });

            entity.Property(e => e.REFERENCIA).HasMaxLength(50);
            entity.Property(e => e.DESCRIPCION).HasMaxLength(100);
            entity.Property(e => e.DESCRIPCION_DEPTO).HasMaxLength(50);
            entity.Property(e => e.UNIDADMEDIDA).HasMaxLength(15);

            entity.HasOne(d => d.IDNavigation).WithMany(p => p.IT_INV_MENSUALES_LIN)
                .HasForeignKey(d => d.ID)
                .HasConstraintName("FK_IT_INV_MENSUALES_LIN_ID");
        });

        modelBuilder.Entity<IT_PEDIDOS_CAB>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_IT_PEDIDOS_CAB_ID");

            entity.HasIndex(e => e.ID, "KEY_IT_PEDIDOS_CAB_ID").IsUnique();

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHA).HasColumnType("date");
        });

        modelBuilder.Entity<IT_PEDIDOS_LIN>(entity =>
        {
            entity.HasKey(e => new { e.ID_CAB, e.CODALMACEN, e.CODARTICULO, e.REFERENCIA }).HasName("PK_IT_PEDIDOS_LIN_ID_CAB");

            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.REFERENCIA)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SEMAFORO).HasDefaultValueSql("((0))");
            entity.Property(e => e.SUGERIDO).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.ID_CABNavigation).WithMany(p => p.IT_PEDIDOS_LIN)
                .HasForeignKey(d => d.ID_CAB)
                .HasConstraintName("FK_IT_PEDIDOS_LIN_ID_CAB");
        });

        modelBuilder.Entity<IT_PEDIDOS_NUMPEDIDOS_CAB>(entity =>
        {
            entity.HasKey(e => new { e.ID, e.NUMSERIE, e.CODALMACEN, e.NUMPEDIDO });

            entity.HasIndex(e => new { e.ID, e.NUMSERIE, e.CODALMACEN, e.NUMPEDIDO }, "KEY_IT_PEDIDOS_NUMPEDIDOS_CAB_").IsUnique();

            entity.Property(e => e.NUMSERIE)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHAPEDIDO).HasColumnType("datetime");
        });

        modelBuilder.Entity<IT_PEDIDOS_NUMPEDIDOS_LIN>(entity =>
        {
            entity.HasKey(e => new { e.ID_CAB, e.NUMSERIE, e.CODALMACEN, e.NUMPEDIDO, e.NUMLINEA });

            entity.Property(e => e.NUMSERIE)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODIGO)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.REFERENCIA)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.REFERENCIA2)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");

            entity.HasOne(d => d.IT_PEDIDOS_NUMPEDIDOS_CAB).WithMany(p => p.IT_PEDIDOS_NUMPEDIDOS_LIN)
                .HasForeignKey(d => new { d.ID_CAB, d.NUMSERIE, d.CODALMACEN, d.NUMPEDIDO })
                .HasConstraintName("FK_IT_PEDIDOS_NUMPEDIDOS_LIN_ID_CAB");
        });

        modelBuilder.Entity<IT_PERFILES>(entity =>
        {
            entity.HasKey(e => e.tipoUsuario).HasName("PK_IT_PERFILES_tipoUsuario");

            entity.Property(e => e.tipoUsuario).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MONEDAS>(entity =>
        {
            entity.HasKey(e => e.CODMONEDA).HasName("MONEDAS_PK");

            entity.HasIndex(e => e.VERSION, "IDX_MONEDASVERSION");

            entity.Property(e => e.CODMONEDA).ValueGeneratedNever();
            entity.Property(e => e.APLICARCOTDEF)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.CAMBIOOTRAMONEDA)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.CODIGOISO).HasMaxLength(10);
            entity.Property(e => e.CODIGOISONUM).HasMaxLength(3);
            entity.Property(e => e.COMISIONCAMBIO).HasDefaultValueSql("((0))");
            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.IMAGEN).HasColumnType("image");
            entity.Property(e => e.IMAGEN_PNG).HasColumnType("image");
            entity.Property(e => e.INICIALES)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.INICIALESDELANTE)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.MORA).HasDefaultValueSql("((0))");
            entity.Property(e => e.NUMERADOR)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.PRINCIPAL)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.VERSION)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<MOVIMENTS>(entity =>
        {
            entity.HasKey(e => e.ID)
                .HasName("MOVIMENTS_PK")
                .IsClustered(false);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("COMPROBARNULOSMOVIMENTSAI");
                    tb.HasTrigger("COMPROBARNULOSMOVIMENTSBD");
                    tb.HasTrigger("DELETESTOCKSTRASPASOS");
                    tb.HasTrigger("STOCKSTRASPASOS");
                });

            entity.HasIndex(e => new { e.SERIEDOC, e.NUMDOC }, "MOVIMENST_SERIEDOCNUMDOC");

            entity.HasIndex(e => new { e.CODARTICULO, e.TALLA, e.COLOR, e.CODALMACENDESTINO }, "MOVIMENTS_ARTIC_ALM_DEST");

            entity.HasIndex(e => new { e.CODARTICULO, e.TALLA, e.COLOR, e.CODALMACENORIGEN }, "MOVIMENTS_ARTIC_ALM_ORIG");

            entity.HasIndex(e => new { e.FECHA, e.CODALMACENORIGEN, e.TIPO }, "MOVIMENTS_FECHAALM");

            entity.HasIndex(e => e.NUMDOC, "MOVIMENTS_NUMDOC");

            entity.HasIndex(e => new { e.TIPO, e.CODALMACENDESTINO, e.CODARTICULO, e.TALLA, e.COLOR, e.FECHA }, "MOVIMENTS_STOCK_DESTINO");

            entity.HasIndex(e => new { e.TIPO, e.CODALMACENORIGEN, e.CODARTICULO, e.TALLA, e.COLOR, e.FECHA }, "MOVIMENTS_STOCK_ORIGEN");

            entity.HasIndex(e => new { e.TIPO, e.SERIEDOC, e.NUMDOC }, "MOVIMENTS_TIPO");

            entity.Property(e => e.CAJA)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CALCMOVPOST)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.CODALMACENDESTINO)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODALMACENORIGEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODMONEDAPVP).HasDefaultValueSql("((0))");
            entity.Property(e => e.COLOR)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("('.')")
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHA).HasColumnType("datetime");
            entity.Property(e => e.HORA).HasColumnType("datetime");
            entity.Property(e => e.NUMSERIE)
                .HasMaxLength(25)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PVP).HasDefaultValueSql("((0))");
            entity.Property(e => e.SERIECOMPRA)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SERIEDOC)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.STOCK).HasDefaultValueSql("((0))");
            entity.Property(e => e.STOCK2).HasDefaultValueSql("((0))");
            entity.Property(e => e.TALLA)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("('.')")
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TIPO)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ZONA).HasMaxLength(50);
        });

        modelBuilder.Entity<PEDCOMPRACAB>(entity =>
        {
            entity.HasKey(e => new { e.NUMSERIE, e.NUMPEDIDO, e.N }).HasName("PEDCOMPRACAB_PK");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("PEDCOMPRACAB_CHANGE");
                    tb.HasTrigger("PEDCOMPRACAB_INSERT");
                    tb.HasTrigger("PEDCOMPRACAB_INSERT_CREARCAMPOSLIBRES");
                });

            entity.HasIndex(e => new { e.NUMSERIE, e.NUMPEDIDO, e.N }, "PEDCOMPRACAB_DESC").IsDescending();

            entity.HasIndex(e => e.FECHAPEDIDO, "PEDCOMPRACAB_FECHA");

            entity.HasIndex(e => e.CODPROVEEDOR, "PEDCOMPRACAB_PROVEEDOR");

            entity.HasIndex(e => e.SUPEDIDO, "PEDCOMPRACAB_SUPEDIDO");

            entity.Property(e => e.NUMSERIE)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.N)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.ENVIOPOR)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHACREACION).HasColumnType("datetime");
            entity.Property(e => e.FECHAENTREGA).HasColumnType("datetime");
            entity.Property(e => e.FECHAMODIFICADO).HasColumnType("datetime");
            entity.Property(e => e.FECHAPEDIDO).HasColumnType("datetime");
            entity.Property(e => e.FROMPEDVENTACENTRAL)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.HORA).HasColumnType("datetime");
            entity.Property(e => e.IVAINCLUIDO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.NALBARAN)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.NORECIBIDO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.PORTESPAG)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.REGIMFACT).HasMaxLength(1);
            entity.Property(e => e.SERIEALBARAN).HasMaxLength(4);
            entity.Property(e => e.SUPEDIDO)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TODORECIBIDO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.TRANSPORTE).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<PEDCOMPRALIN>(entity =>
        {
            entity.HasKey(e => new { e.NUMSERIE, e.NUMPEDIDO, e.N, e.NUMLINEA }).HasName("PEDCOMPRALIN_PK");

            entity.ToTable(tb => tb.HasTrigger("PEDCOMPRALIN_CHANGE"));

            entity.HasIndex(e => e.CODARTICULO, "PEDCOMPRALINPORCODARTIC");

            entity.HasIndex(e => new { e.CODARTICULO, e.COLOR, e.TALLA }, "PEDCOMPRALIN_CODCOLORTALLA");

            entity.HasIndex(e => e.SUPEDIDO, "PEDCOMPRALIN_SUPEDIDO");

            entity.Property(e => e.NUMSERIE)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.N)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.COLOR)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("('.')")
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DEPOSITO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(40)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DTOTEXTO).HasMaxLength(60);
            entity.Property(e => e.ESOFERTA)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.FECHAENTREGA).HasColumnType("datetime");
            entity.Property(e => e.LINEAOCULTA)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.REFERENCIA)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SUPEDIDO).HasMaxLength(15);
            entity.Property(e => e.TALLA)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("('.')")
                .UseCollation("Latin1_General_CS_AI");

            entity.HasOne(d => d.NNavigation).WithMany(p => p.PEDCOMPRALIN)
                .HasForeignKey(d => new { d.NUMSERIE, d.NUMPEDIDO, d.N })
                .HasConstraintName("PEDCOMPRALIN_FK");
        });

        modelBuilder.Entity<PEDCOMPRATOT>(entity =>
        {
            entity.HasKey(e => new { e.SERIE, e.NUMERO, e.N, e.NUMLINEA }).HasName("PEDCOMPRATOT_PK");

            entity.ToTable(tb => tb.HasTrigger("PEDCOMPRATOT_CHANGE"));

            entity.Property(e => e.SERIE)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.N)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(40)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ESGASTO)
                .HasMaxLength(1)
                .IsFixedLength();

            entity.HasOne(d => d.PEDCOMPRACAB).WithMany(p => p.PEDCOMPRATOT)
                .HasForeignKey(d => new { d.SERIE, d.NUMERO, d.N })
                .HasConstraintName("PEDCOMPRATOT_FK");
        });

        modelBuilder.Entity<PROVEEDORES>(entity =>
        {
            entity.HasKey(e => e.CODPROVEEDOR).HasName("PROVEEDORES_PK");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("PROVEEDORES_CHANGE");
                    tb.HasTrigger("PROVEEDORES_INSERT");
                    tb.HasTrigger("PROVEEDORES_INSERT_CREARCAMPOSLIBRES");
                });

            entity.HasIndex(e => e.VERSION, "IDX_PROVEEDORESVERSION");

            entity.Property(e => e.CODPROVEEDOR).ValueGeneratedNever();
            entity.Property(e => e.ALIAS)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.APTOCORREOS)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.BLOQUEADO).HasMaxLength(1);
            entity.Property(e => e.CIF)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODBANCO)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODCLISUYO)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODCONTABLE)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODCONTABLECOMPRA).HasMaxLength(12);
            entity.Property(e => e.CODCONTABLEDMN)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODIGOIBAN).HasMaxLength(100);
            entity.Property(e => e.CODPAIS).HasMaxLength(2);
            entity.Property(e => e.CODPOSTAL)
                .HasMaxLength(8)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODPOSTALBANCO)
                .HasMaxLength(8)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODSWIFT)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODTALLA)
                .HasMaxLength(10)
                .HasDefaultValueSql("('.')")
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.COMPRARIVAINCLUIDO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.COMPRARSINIMPUESTOS)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.CUOTAIVADEDUCIBLE).HasDefaultValueSql("((0))");
            entity.Property(e => e.DESCATALOGADO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.DIGCONTROLBANCO)
                .HasMaxLength(2)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DIRECCION1)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DIRECCION2)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DIRECCIONBANCO)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ENVIOCODPAIS).HasMaxLength(2);
            entity.Property(e => e.ENVIOCODPOSTAL)
                .HasMaxLength(8)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ENVIODIRECION)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ENVIOPAIS)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ENVIOPOBLACION)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ENVIOPOR)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ENVIOPROVINCIA)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.ESPROVDELGRUPO).HasDefaultValueSql("((0))");
            entity.Property(e => e.E_MAIL)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FAX)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FAXPEDIDOS)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHAMODIFICADO).HasColumnType("datetime");
            entity.Property(e => e.MOBIL).HasMaxLength(15);
            entity.Property(e => e.NIF20)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NOACOGIDOROI).HasDefaultValueSql("((0))");
            entity.Property(e => e.NOMBREBANCO)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NOMCOMERCIAL)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NOMPROVEEDOR)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NUMCUENTA)
                .HasMaxLength(10)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NUMSUCURSAL)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.OBSERVACIONES).HasColumnType("ntext");
            entity.Property(e => e.ORDENADEUDO).HasMaxLength(35);
            entity.Property(e => e.PAIS)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PERSONACONTACTO)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PERSONAJURIDICA).HasMaxLength(1);
            entity.Property(e => e.POBLACION)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.POBLACIONBANCO)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PROVINCIA)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.REGIMFACT).HasMaxLength(1);
            entity.Property(e => e.REGIMRET).HasMaxLength(1);
            entity.Property(e => e.REGIMRETICA).HasMaxLength(1);
            entity.Property(e => e.RET_FECHAFINEXCLUSION).HasColumnType("datetime");
            entity.Property(e => e.RET_FECHAINIEXCLUSION).HasColumnType("datetime");
            entity.Property(e => e.SERIE)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SERIEALBINDIRECTA)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SERIEFACINDIRECTA)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TELEFONO1)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TELEFONO2)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TELEX)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TIPOPORTES).HasMaxLength(1);
            entity.Property(e => e.TRANSPORTE).HasDefaultValueSql("((0))");
            entity.Property(e => e.VENCIMSEGUN).HasDefaultValueSql("((0))");
            entity.Property(e => e.VERSION)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<REM_FRONTS>(entity =>
        {
            entity.HasKey(e => e.IDFRONT);

            entity.ToTable(tb => tb.HasTrigger("REM_FRONTS_CHANGE"));

            entity.Property(e => e.IDFRONT).ValueGeneratedNever();
            entity.Property(e => e.ACCESOSARTICULO)
                .HasMaxLength(60)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.AEROPUERTO_AENA).HasMaxLength(3);
            entity.Property(e => e.ALMACEN).HasMaxLength(3);
            entity.Property(e => e.ALMACENDOBLECOSTE)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.AUDITORIA).HasMaxLength(60);
            entity.Property(e => e.BLOQUEADO).HasMaxLength(1);
            entity.Property(e => e.CAJAFUERTE).HasMaxLength(3);
            entity.Property(e => e.CIF).HasMaxLength(20);
            entity.Property(e => e.COBROS_REMOTOS).HasMaxLength(1);
            entity.Property(e => e.CODALMACENCENTRAL)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODALMCOSTES)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODCONTABLEVARIOS)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODPOSTAL).HasMaxLength(8);
            entity.Property(e => e.CONTRATO_AENA).HasMaxLength(30);
            entity.Property(e => e.CRC).HasMaxLength(50);
            entity.Property(e => e.CUETAGASTOSREDONDEO).HasMaxLength(12);
            entity.Property(e => e.CUETAINGRESOSREDONDEO).HasMaxLength(12);
            entity.Property(e => e.DATOSPROVEEDOR)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.DESCIDFISCAL).HasMaxLength(15);
            entity.Property(e => e.DESCTASA1).HasMaxLength(15);
            entity.Property(e => e.DESCTASA2).HasMaxLength(15);
            entity.Property(e => e.DIRECCION).HasMaxLength(255);
            entity.Property(e => e.DIRECCION2).HasMaxLength(255);
            entity.Property(e => e.DIRECTORIO).HasMaxLength(255);
            entity.Property(e => e.DIRECTORIOFTP).HasMaxLength(255);
            entity.Property(e => e.EMAIL).HasMaxLength(255);
            entity.Property(e => e.ENLACEPROMOCIONESIP).HasMaxLength(40);
            entity.Property(e => e.ENTIDADESEXPORT).HasMaxLength(50);
            entity.Property(e => e.ENTIDADESIMPORT).HasMaxLength(100);
            entity.Property(e => e.ERRORDESCARGAFTP).HasColumnType("ntext");
            entity.Property(e => e.ESPACIOFISCAL).HasMaxLength(10);
            entity.Property(e => e.FAX).HasMaxLength(15);
            entity.Property(e => e.FECHABLOQUEO).HasColumnType("datetime");
            entity.Property(e => e.FECHAPETICIONDESCARGA).HasColumnType("datetime");
            entity.Property(e => e.FECHAULTIMADESCARGA).HasColumnType("datetime");
            entity.Property(e => e.FLAGSDESCARGASAUTO).HasMaxLength(255);
            entity.Property(e => e.FPAGOFOODSTAMP).HasMaxLength(6);
            entity.Property(e => e.GRUPORECURSO).HasDefaultValueSql("((-1))");
            entity.Property(e => e.HORADESCARGASAUTO).HasColumnType("datetime");
            entity.Property(e => e.IDIVA).HasMaxLength(25);
            entity.Property(e => e.IMPARTICCOMPRA).HasMaxLength(50);
            entity.Property(e => e.IMPARTICESPCOMPRA).HasMaxLength(50);
            entity.Property(e => e.IMPARTICESPVENTA).HasMaxLength(50);
            entity.Property(e => e.IMPUESTOARTIC).HasMaxLength(50);
            entity.Property(e => e.INICIALIZACION).HasMaxLength(40);
            entity.Property(e => e.LICENCIA).HasMaxLength(25);
            entity.Property(e => e.LOCAL_AENA).HasMaxLength(50);
            entity.Property(e => e.LOGO).HasColumnType("image");
            entity.Property(e => e.MOTIVOBLOQUEOAUTOMATICO).HasMaxLength(1000);
            entity.Property(e => e.NAFCODE).HasMaxLength(25);
            entity.Property(e => e.NOMBRE).HasMaxLength(255);
            entity.Property(e => e.NOMBRECOMERCIAL).HasMaxLength(255);
            entity.Property(e => e.NOMBRECOMERCIAL2).HasMaxLength(255);
            entity.Property(e => e.NUMCRC).HasMaxLength(50);
            entity.Property(e => e.NUMPOLICIA).HasMaxLength(10);
            entity.Property(e => e.OPCIONESASUNTOS).HasMaxLength(30);
            entity.Property(e => e.OPCIONESCENTRAL).HasMaxLength(50);
            entity.Property(e => e.PAIS).HasMaxLength(10);
            entity.Property(e => e.PASSW)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PASSWORDFTP).HasMaxLength(50);
            entity.Property(e => e.PLANTILLAVENTA).HasMaxLength(20);
            entity.Property(e => e.POBLACION).HasMaxLength(100);
            entity.Property(e => e.PROTECCIONHARDWARE)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PROVINCIA).HasMaxLength(100);
            entity.Property(e => e.RAIZANTICIPOSCLIENTE).HasMaxLength(12);
            entity.Property(e => e.RAIZANTICIPOSDEUDOR).HasMaxLength(12);
            entity.Property(e => e.RAIZCONTABLEACREEDOR).HasMaxLength(12);
            entity.Property(e => e.RAIZCONTABLECOD)
                .HasMaxLength(12)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.RAIZCONTABLEDEUDOR).HasMaxLength(12);
            entity.Property(e => e.RAIZCONTABLEPROV).HasMaxLength(12);
            entity.Property(e => e.RAIZRECARGASGRATIS).HasMaxLength(12);
            entity.Property(e => e.REGIMFACTSIMPL).HasMaxLength(1);
            entity.Property(e => e.SERVERFREMOTE).HasMaxLength(40);
            entity.Property(e => e.SERVERFTP).HasMaxLength(40);
            entity.Property(e => e.TELEFONO).HasMaxLength(15);
            entity.Property(e => e.TERMINALFTP).HasMaxLength(40);
            entity.Property(e => e.TITPLANTILLARET)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TITULO)
                .HasMaxLength(45)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TSERVER)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.ULTACTSTOCKS).HasColumnType("datetime");
            entity.Property(e => e.USUARIO)
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.USUARIOFTP).HasMaxLength(50);
            entity.Property(e => e.VALES_REMOTOS).HasMaxLength(1);
            entity.Property(e => e.VALIDARCLIICGSII).HasMaxLength(1);
        });

        modelBuilder.Entity<SUCURSALES>(entity =>
        {
            entity.HasKey(e => e.IDSUCURSAL).HasName("SUCURSALES_PK");

            entity.Property(e => e.IDSUCURSAL).ValueGeneratedNever();
            entity.Property(e => e.DESCRIPCION).HasMaxLength(80);
            entity.Property(e => e.PASS).HasMaxLength(8);
            entity.Property(e => e.USUARIO).HasMaxLength(15);
        });

        modelBuilder.Entity<VENDEDORES>(entity =>
        {
            entity.HasKey(e => e.CODVENDEDOR).HasName("VENDEDORES_PK");

            entity.ToTable(tb => tb.HasTrigger("VENDEDORES_INSERT_HIOPOS"));

            entity.HasIndex(e => e.VERSION, "IDX_VENDEDORESVERSION");

            entity.Property(e => e.CODVENDEDOR).ValueGeneratedNever();
            entity.Property(e => e.ACTIVO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.BLOQUEADO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.CENTROCOSTE).HasMaxLength(6);
            entity.Property(e => e.CODALMACEN)
                .HasMaxLength(3)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODBANCO).HasMaxLength(4);
            entity.Property(e => e.CODCONTABLE).HasMaxLength(12);
            entity.Property(e => e.CODIGOIBAN).HasMaxLength(100);
            entity.Property(e => e.CODPOSTAL)
                .HasMaxLength(8)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.CODPOSTALBANCO).HasMaxLength(8);
            entity.Property(e => e.CODSWIFT).HasMaxLength(15);
            entity.Property(e => e.COLOR)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.DESCATALOGADO)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.DIGCONTROLBANCO).HasMaxLength(2);
            entity.Property(e => e.DIRECCION)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.DIRECCIONBANCO).HasMaxLength(20);
            entity.Property(e => e.DNI)
                .HasMaxLength(18)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.EMAIL).HasMaxLength(255);
            entity.Property(e => e.FAX)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.FECHACADUCIDADPASS).HasColumnType("datetime");
            entity.Property(e => e.FECHAENTRADA).HasColumnType("datetime");
            entity.Property(e => e.FECHANACIM).HasColumnType("datetime");
            entity.Property(e => e.FOTO).HasColumnType("image");
            entity.Property(e => e.LUGARNACIM)
                .HasMaxLength(25)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.MOBIL)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NEWPASSENTRADA)
                .HasMaxLength(30)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NEWPASSREGISTRO)
                .HasMaxLength(30)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NOMBREBANCO).HasMaxLength(20);
            entity.Property(e => e.NOMBRECORTO).HasMaxLength(10);
            entity.Property(e => e.NOMVENDEDOR)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NUMCUENTA).HasMaxLength(10);
            entity.Property(e => e.NUMSSOCIAL)
                .HasMaxLength(18)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.NUMSUCURSAL).HasMaxLength(4);
            entity.Property(e => e.OBSERVACIONES).HasColumnType("ntext");
            entity.Property(e => e.PASSENTRADA)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PASSREGISTRO)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PASSWORDENTRADARFID)
                .HasMaxLength(40)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PASSWORDREGISTRORFID)
                .HasMaxLength(40)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.PASSWORDWEB)
                .HasMaxLength(8)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.POBLACION)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.POBLACIONBANCO).HasMaxLength(20);
            entity.Property(e => e.PROVINCIA)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.SERIENOMINA)
                .HasMaxLength(4)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.TALLA)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.TELEFONO)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.USUARIOCENTRALITA)
                .HasMaxLength(16)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.USUARIOWEB)
                .HasMaxLength(15)
                .UseCollation("Latin1_General_CS_AI");
            entity.Property(e => e.VERSION)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}