// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class MONEDAS
{
    public int CODMONEDA { get; set; }

    public string DESCRIPCION { get; set; }

    public string INICIALES { get; set; }

    public double? CANTIDADPRIN { get; set; }

    public double? CANTIDADSEC { get; set; }

    public short? NUMDECIMALES { get; set; }

    public string NUMERADOR { get; set; }

    public string PRINCIPAL { get; set; }

    public byte[] IMAGEN { get; set; }

    public double? COTDEF { get; set; }

    public string APLICARCOTDEF { get; set; }

    public double? MORA { get; set; }

    public double? COMISIONCAMBIO { get; set; }

    public string INICIALESDELANTE { get; set; }

    public byte[] VERSION { get; set; }

    public byte[] IMAGEN_PNG { get; set; }

    public string CODIGOISO { get; set; }

    public string CODIGOISONUM { get; set; }

    public string CAMBIOOTRAMONEDA { get; set; }
}