// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class PEDCOMPRALIN
{
    public string NUMSERIE { get; set; }

    public int NUMPEDIDO { get; set; }

    public string N { get; set; }

    public int NUMLINEA { get; set; }

    public int? CODARTICULO { get; set; }

    public string REFERENCIA { get; set; }

    public string TALLA { get; set; }

    public string COLOR { get; set; }

    public string DESCRIPCION { get; set; }

    public double? UNID1 { get; set; }

    public double? UNID2 { get; set; }

    public double? UNID3 { get; set; }

    public double? UNID4 { get; set; }

    public double? UNIDADESTOTAL { get; set; }

    public double? UNIDADESREC { get; set; }

    public double? UNIDADESPEN { get; set; }

    public double? PRECIO { get; set; }

    public double? DTO { get; set; }

    public short? TIPOIMPUESTO { get; set; }

    public double? IVA { get; set; }

    public double? REQ { get; set; }

    public double? TOTALLINEA { get; set; }

    public string CODALMACEN { get; set; }

    public string DEPOSITO { get; set; }

    public double? PRECIOVENTA { get; set; }

    public double? NUMKG { get; set; }

    public string SUPEDIDO { get; set; }

    public int? CODCLIENTE { get; set; }

    public double? CARGO1 { get; set; }

    public double? CARGO2 { get; set; }

    public string DTOTEXTO { get; set; }

    public string ESOFERTA { get; set; }

    public DateTime? FECHAENTREGA { get; set; }

    public int? CODENVIO { get; set; }

    public double? UDMEDIDA2 { get; set; }

    public string LINEAOCULTA { get; set; }

    public int? CODFORMATO { get; set; }

    public virtual PEDCOMPRACAB NNavigation { get; set; }
}