// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class PEDCOMPRACAB
{
    public string NUMSERIE { get; set; }

    public int NUMPEDIDO { get; set; }

    public string N { get; set; }

    public int? CODPROVEEDOR { get; set; }

    public string SERIEALBARAN { get; set; }

    public int? NUMEROALBARAN { get; set; }

    public string NALBARAN { get; set; }

    public DateTime? FECHAPEDIDO { get; set; }

    public DateTime? FECHAENTREGA { get; set; }

    public string ENVIOPOR { get; set; }

    public double? TOTBRUTO { get; set; }

    public double? DTOPP { get; set; }

    public double? TOTDTOPP { get; set; }

    public double? DTOCOMERCIAL { get; set; }

    public double? TOTDTOCOMERCIAL { get; set; }

    public double? TOTIMPUESTOS { get; set; }

    public double? TOTNETO { get; set; }

    public int? CODMONEDA { get; set; }

    public double? FACTORMONEDA { get; set; }

    public string PORTESPAG { get; set; }

    public string SUPEDIDO { get; set; }

    public string IVAINCLUIDO { get; set; }

    public string TODORECIBIDO { get; set; }

    public int? TIPODOC { get; set; }

    public int? IDESTADO { get; set; }

    public DateTime? FECHAMODIFICADO { get; set; }

    public DateTime? HORA { get; set; }

    public int? TRANSPORTE { get; set; }

    public int? NBULTOS { get; set; }

    public double? TOTALCARGOSDTOS { get; set; }

    public string NORECIBIDO { get; set; }

    public int? CODEMPLEADO { get; set; }

    public int? CONTACTO { get; set; }

    public string FROMPEDVENTACENTRAL { get; set; }

    public DateTime? FECHACREACION { get; set; }

    public int? NUMIMPRESIONES { get; set; }

    public string REGIMFACT { get; set; }

    public virtual ICollection<PEDCOMPRALIN> PEDCOMPRALIN { get; } = new List<PEDCOMPRALIN>();

    public virtual ICollection<PEDCOMPRATOT> PEDCOMPRATOT { get; } = new List<PEDCOMPRATOT>();
}