// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class PEDCOMPRATOT
{
    public string SERIE { get; set; }

    public int NUMERO { get; set; }

    public string N { get; set; }

    public int NUMLINEA { get; set; }

    public double? BRUTO { get; set; }

    public double? DTOCOMERC { get; set; }

    public double? TOTDTOCOMERC { get; set; }

    public double? DTOPP { get; set; }

    public double? TOTDTOPP { get; set; }

    public double? BASEIMPONIBLE { get; set; }

    public double? IVA { get; set; }

    public double? TOTIVA { get; set; }

    public double? REQ { get; set; }

    public double? TOTREQ { get; set; }

    public double? TOTAL { get; set; }

    public string ESGASTO { get; set; }

    public int? CODDTO { get; set; }

    public string DESCRIPCION { get; set; }

    public int? TIPOIVA { get; set; }

    public virtual PEDCOMPRACAB PEDCOMPRACAB { get; set; }
}