// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class PROVEEDORES
{
    public int CODPROVEEDOR { get; set; }

    public string CODCONTABLE { get; set; }

    public string NOMPROVEEDOR { get; set; }

    public string NOMCOMERCIAL { get; set; }

    public string CIF { get; set; }

    public string NIF20 { get; set; }

    public string ALIAS { get; set; }

    public string DIRECCION1 { get; set; }

    public string CODPOSTAL { get; set; }

    public string POBLACION { get; set; }

    public string PROVINCIA { get; set; }

    public string PAIS { get; set; }

    public string PERSONACONTACTO { get; set; }

    public string TELEFONO1 { get; set; }

    public string TELEFONO2 { get; set; }

    public string FAX { get; set; }

    public string FAXPEDIDOS { get; set; }

    public string TELEX { get; set; }

    public string E_MAIL { get; set; }

    public string CODCLISUYO { get; set; }

    public string NUMCUENTA { get; set; }

    public string CODBANCO { get; set; }

    public string NUMSUCURSAL { get; set; }

    public string DIGCONTROLBANCO { get; set; }

    public string CODPOSTALBANCO { get; set; }

    public string NOMBREBANCO { get; set; }

    public string DIRECCIONBANCO { get; set; }

    public string POBLACIONBANCO { get; set; }

    public string CODSWIFT { get; set; }

    public string ENVIOPOR { get; set; }

    public string ENVIODIRECION { get; set; }

    public string ENVIOCODPOSTAL { get; set; }

    public string ENVIOPOBLACION { get; set; }

    public string ENVIOPROVINCIA { get; set; }

    public string ENVIOPAIS { get; set; }

    public double? CANTPORTESPAG { get; set; }

    public string TIPOPORTES { get; set; }

    public int? NUMDIASENTREGA { get; set; }

    public string OBSERVACIONES { get; set; }

    public string CODTALLA { get; set; }

    public string COMPRARSINIMPUESTOS { get; set; }

    public string COMPRARIVAINCLUIDO { get; set; }

    public string APTOCORREOS { get; set; }

    public double? DTOCOMERCIAL { get; set; }

    public short? TIPO { get; set; }

    public string REGIMFACT { get; set; }

    public int? CODMONEDA { get; set; }

    public short? DIAPAGO1 { get; set; }

    public short? DIAPAGO2 { get; set; }

    public DateTime? FECHAMODIFICADO { get; set; }

    public string DIRECCION2 { get; set; }

    public int? TRANSPORTE { get; set; }

    public int? CODIDIOMA { get; set; }

    public int? TIPODOC { get; set; }

    public string SERIEALBINDIRECTA { get; set; }

    public string SERIEFACINDIRECTA { get; set; }

    public int? B2B_ORIGEN { get; set; }

    public int? B2B_IDMAPPING { get; set; }

    public int? CODCENTRAL { get; set; }

    public int? CODVISIBLE { get; set; }

    public int? VENCIMSEGUN { get; set; }

    public string CODPAIS { get; set; }

    public string ENVIOCODPAIS { get; set; }

    public int? B2B_ORIGENPEDIDO { get; set; }

    public int? B2B_IDMAPPINGPEDIDO { get; set; }

    public int? CODCENTRALPEDIDO { get; set; }

    public int? NUMDIASCANCELACION { get; set; }

    public double? PEDIDOMINIMO { get; set; }

    public int? FACTURARCONIMPUESTO { get; set; }

    public string CODCONTABLECOMPRA { get; set; }

    public string DESCATALOGADO { get; set; }

    public string CODIGOIBAN { get; set; }

    public string CODCONTABLEDMN { get; set; }

    public int? PEDIDOSVENCIMSEGUN { get; set; }

    public string MOBIL { get; set; }

    public bool? ESPROVDELGRUPO { get; set; }

    public string REGIMRET { get; set; }

    public int? TIPORET { get; set; }

    public int? RET_TIPORETENCIONIVA { get; set; }

    public double? RET_PORCEXCLUSION { get; set; }

    public DateTime? RET_FECHAINIEXCLUSION { get; set; }

    public DateTime? RET_FECHAFINEXCLUSION { get; set; }

    public bool IVANODEDUCIBLE { get; set; }

    public bool RECC { get; set; }

    public string BLOQUEADO { get; set; }

    public string ORDENADEUDO { get; set; }

    public int? TIPODOCIDENT { get; set; }

    public int? CODEMPRESACONTABLE { get; set; }

    public string PERSONAJURIDICA { get; set; }

    public bool? CUOTAIVADEDUCIBLE { get; set; }

    public double? PORCCUOTAIVADEDUCIBLE { get; set; }

    public string REGIMRETICA { get; set; }

    public bool? NOACOGIDOROI { get; set; }

    public string SERIE { get; set; }

    public string ALMACEN { get; set; }

    public byte[] VERSION { get; set; }
}