// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class REM_FRONTS
{
    public int IDFRONT { get; set; }

    public string TITULO { get; set; }

    public short? TIPO { get; set; }

    public string USUARIO { get; set; }

    public string PASSW { get; set; }

    public string ACCESOSARTICULO { get; set; }

    public int? CODCLIENTE { get; set; }

    public int? CODPROVEEDOR { get; set; }

    public bool? ESCLIENTE { get; set; }

    public bool? FILTRARVENDEDORES { get; set; }

    public bool? FILTRARCLIENTES { get; set; }

    public bool? FILTRARPROVEEDORES { get; set; }

    public string CODCONTABLEVARIOS { get; set; }

    public string RAIZCONTABLECOD { get; set; }

    public bool? FILTRARFPAGO { get; set; }

    public bool? CLIENTEUNICO { get; set; }

    public int? CODCLIENTEUNICO { get; set; }

    public string OPCIONESCENTRAL { get; set; }

    public string INICIALIZACION { get; set; }

    public string CIF { get; set; }

    public string NOMBRE { get; set; }

    public string NOMBRECOMERCIAL { get; set; }

    public string DIRECCION { get; set; }

    public string CODPOSTAL { get; set; }

    public string POBLACION { get; set; }

    public string PROVINCIA { get; set; }

    public string EMAIL { get; set; }

    public string DESCTASA1 { get; set; }

    public string DESCTASA2 { get; set; }

    public string TELEFONO { get; set; }

    public string FAX { get; set; }

    public byte[] LOGO { get; set; }

    public string DESCIDFISCAL { get; set; }

    public string COBROS_REMOTOS { get; set; }

    public string VALES_REMOTOS { get; set; }

    public string SERVERFTP { get; set; }

    public string DIRECTORIOFTP { get; set; }

    public int? PUERTOFTP { get; set; }

    public string USUARIOFTP { get; set; }

    public string PASSWORDFTP { get; set; }

    public string TERMINALFTP { get; set; }

    public string DIRECTORIO { get; set; }

    public int? ESTADOFTP { get; set; }

    public string ERRORDESCARGAFTP { get; set; }

    public string TSERVER { get; set; }

    public int? CODIDIOMA { get; set; }

    public int? FRECUENCIAIMPORT { get; set; }

    public string ENTIDADESIMPORT { get; set; }

    public int? FRECUENCIAEXPORT { get; set; }

    public string ENTIDADESEXPORT { get; set; }

    public string PLANTILLAVENTA { get; set; }

    public string OPCIONESASUNTOS { get; set; }

    public int? IDHOTEL { get; set; }

    public bool? FILTRARPROMOCIONES { get; set; }

    public string IMPUESTOARTIC { get; set; }

    public string CUETAGASTOSREDONDEO { get; set; }

    public string CUETAINGRESOSREDONDEO { get; set; }

    public int? TIPOIMPUESTODEF { get; set; }

    public int? FRECUENCIACONEXION { get; set; }

    public bool? USAFOODSTAMP { get; set; }

    public string FPAGOFOODSTAMP { get; set; }

    public int? TIPOARTFOODSTAMP { get; set; }

    public string AUDITORIA { get; set; }

    public string DATOSPROVEEDOR { get; set; }

    public string NOMBRECOMERCIAL2 { get; set; }

    public string DIRECCION2 { get; set; }

    public string RAIZCONTABLEPROV { get; set; }

    public string RAIZCONTABLEDEUDOR { get; set; }

    public string RAIZCONTABLEACREEDOR { get; set; }

    public bool? NOCALCPRECIOSIMPORT { get; set; }

    public int? VERSIONEXE { get; set; }

    public byte? DOBLECOSTE { get; set; }

    public string ALMACENDOBLECOSTE { get; set; }

    public int? TARIFAVDOBLECOSTE { get; set; }

    public bool? CAMTA { get; set; }

    public int? GRUPORECURSO { get; set; }

    public bool? FILTRARCONCEPTOSPAGO { get; set; }

    public bool? NOENVIARCLIENTESRANGO { get; set; }

    public bool? FILTRARGRUPOSRECURSOS { get; set; }

    public bool? FILTRARGRUPOSEMPLEADOS { get; set; }

    public bool? CALCULARRIESGOCLIENTE { get; set; }

    public bool? USAFREMOTE { get; set; }

    public string SERVERFREMOTE { get; set; }

    public int? PUERTOFREMOTE { get; set; }

    public bool ABONOSCENTRALIZADOS { get; set; }

    public int? CODMONEDA { get; set; }

    public bool? IGNORARUDSVENTA { get; set; }

    public int? CODCONCEPTODESCUADRE { get; set; }

    public int? CODCONCEPTORETIRADA { get; set; }

    public bool? MODCLI { get; set; }

    public bool? FILTRARMOTIVOSDTO { get; set; }

    public bool? CANCLACT { get; set; }

    public string IMPARTICCOMPRA { get; set; }

    public string RAIZANTICIPOSDEUDOR { get; set; }

    public string RAIZANTICIPOSCLIENTE { get; set; }

    public string TITPLANTILLARET { get; set; }

    public bool? USADESCARGASAUTO { get; set; }

    public DateTime? HORADESCARGASAUTO { get; set; }

    public DateTime? FECHAULTIMADESCARGA { get; set; }

    public DateTime? FECHAPETICIONDESCARGA { get; set; }

    public string FLAGSDESCARGASAUTO { get; set; }

    public string RAIZRECARGASGRATIS { get; set; }

    public int? CODVISCLI { get; set; }

    public bool? FVISIBPROMO { get; set; }

    public bool? FVISIBVEND { get; set; }

    public bool? FVISIBTARIFV { get; set; }

    public bool? FILTRARFAVORITOS { get; set; }

    public bool? COLORESESTSERV { get; set; }

    public bool? IGNORARUDSCOMPRA { get; set; }

    public bool? CLIOBLIGVALES { get; set; }

    public bool? FOTOFPTOTALES { get; set; }

    public bool? CHECKLETRACIF { get; set; }

    public bool? VNSSS { get; set; }

    public int? GENVENTASCLI { get; set; }

    public bool? ACTNUMFISC { get; set; }

    public bool? MOSTNSZ { get; set; }

    public string ALMACEN { get; set; }

    public int? NUMCAJAS { get; set; }

    public string CAJAFUERTE { get; set; }

    public string CODALMACENCENTRAL { get; set; }

    public bool? FILTROCREATARJETAS { get; set; }

    public bool? CONFIGEMAIL { get; set; }

    public string LICENCIA { get; set; }

    public bool? MODCLITARJETAS { get; set; }

    public bool VENTASCLIENTECENTRAL { get; set; }

    public bool? POCKMNGCENTR { get; set; }

    public DateTime? ULTACTSTOCKS { get; set; }

    public bool? FILTROUSOTARJETAS { get; set; }

    public bool? ACTIMMEDIATO { get; set; }

    public bool? DESCATALOGADO { get; set; }

    public bool? USACOSTESXALM { get; set; }

    public string CODALMCOSTES { get; set; }

    public bool? FILTRARALMACENES { get; set; }

    public int? CODCONCEPTOENTRADA { get; set; }

    public string CONTRATO_AENA { get; set; }

    public string AEROPUERTO_AENA { get; set; }

    public string LOCAL_AENA { get; set; }

    public string ESPACIOFISCAL { get; set; }

    public string NUMPOLICIA { get; set; }

    public string CRC { get; set; }

    public string NUMCRC { get; set; }

    public string PAIS { get; set; }

    public int? CODVISIBLE { get; set; }

    public bool? FILTRARCONCEPTOSAJUSTE { get; set; }

    public bool? FILTRARDISENYOSEMAIL { get; set; }

    public bool FILTRARMOTIVOSDESCUADRE { get; set; }

    public bool? FILTRARRUTAS { get; set; }

    public bool? ENVIARCLIENTESRUTAS { get; set; }

    public bool? BLOQUEARBDOTROEQUIPO { get; set; }

    public string PROTECCIONHARDWARE { get; set; }

    public int? DIASNOMODIFDATOS { get; set; }

    public int? SUBTIPO { get; set; }

    public bool? OWNPACK { get; set; }

    public bool? FILTRARMOTIVOSABONO { get; set; }

    public bool? FILTRARMOTIVOSTRASPASO { get; set; }

    public bool? FILTRARTURNOS { get; set; }

    public bool ENVIARPEDIDOSCOMPRAPROVEEDORES { get; set; }

    public bool? NUMFIAVISO { get; set; }

    public double? NUMFICONSU { get; set; }

    public bool? VENFIAVISO { get; set; }

    public int? DIAAVISVEN { get; set; }

    public bool? FILTRARTIPOSSERVICIO { get; set; }

    public bool GRUPOARTTARIFV { get; set; }

    public int? CODGRUPOARTTARIFV { get; set; }

    public bool GRUPOARTTARIFVMODIF { get; set; }

    public string BLOQUEADO { get; set; }

    public DateTime? FECHABLOQUEO { get; set; }

    public int? TIPOBLOQUEO { get; set; }

    public int? USUARIOBLOQUEO { get; set; }

    public string MOTIVOBLOQUEOAUTOMATICO { get; set; }

    public bool? NUMEROSRESOLUCIONPORTIPODOC { get; set; }

    public string IDIVA { get; set; }

    public string NAFCODE { get; set; }

    public string IMPARTICESPCOMPRA { get; set; }

    public string IMPARTICESPVENTA { get; set; }

    public bool? FILTRARPROMOCIONESAENA { get; set; }

    public string ENLACEPROMOCIONESIP { get; set; }

    public int? ENLACEPROMOCIONESPUERTO { get; set; }

    public string VALIDARCLIICGSII { get; set; }

    public bool? ENLACEPROMOCIONESUSAR { get; set; }

    public bool? MODVEND { get; set; }

    public bool? FORMATOCONPRECIO { get; set; }

    public string REGIMFACTSIMPL { get; set; }

    public int? TIPOOPERACION { get; set; }
}