// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class SUCURSALES
{
    public int IDSUCURSAL { get; set; }

    public string DESCRIPCION { get; set; }

    public string USUARIO { get; set; }

    public string PASS { get; set; }
}