// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcWebPage.MLAVID;

public partial class VENDEDORES
{
    public int CODVENDEDOR { get; set; }

    public string NOMVENDEDOR { get; set; }

    public string DIRECCION { get; set; }

    public string CODPOSTAL { get; set; }

    public string POBLACION { get; set; }

    public string PROVINCIA { get; set; }

    public string TELEFONO { get; set; }

    public DateTime? FECHANACIM { get; set; }

    public string LUGARNACIM { get; set; }

    public DateTime? FECHAENTRADA { get; set; }

    public string OBSERVACIONES { get; set; }

    public double? COMISION { get; set; }

    public string FAX { get; set; }

    public string MOBIL { get; set; }

    public double? RETENCION { get; set; }

    public double? IVA { get; set; }

    public double? FIJO { get; set; }

    public byte[] FOTO { get; set; }

    public string PASSENTRADA { get; set; }

    public string PASSREGISTRO { get; set; }

    public int? TIPOUSUARIO { get; set; }

    public string NUMSSOCIAL { get; set; }

    public string DNI { get; set; }

    public string ACTIVO { get; set; }

    public DateTime? FECHACADUCIDADPASS { get; set; }

    public string BLOQUEADO { get; set; }

    public string CODALMACEN { get; set; }

    public int? CODARTICULO { get; set; }

    public string TALLA { get; set; }

    public string COLOR { get; set; }

    public string DESCATALOGADO { get; set; }

    public string NOMBRECORTO { get; set; }

    public int? TIPOEMPLEADO { get; set; }

    public int? CODIGORF { get; set; }

    public double? COSTEHORA { get; set; }

    public double? COSTEHORAEXTRA { get; set; }

    public string USUARIOWEB { get; set; }

    public string PASSWORDWEB { get; set; }

    public string EMAIL { get; set; }

    public string CENTROCOSTE { get; set; }

    public string SERIENOMINA { get; set; }

    public string CODCONTABLE { get; set; }

    public string NUMCUENTA { get; set; }

    public string CODBANCO { get; set; }

    public string NUMSUCURSAL { get; set; }

    public string DIGCONTROLBANCO { get; set; }

    public string CODPOSTALBANCO { get; set; }

    public string CODSWIFT { get; set; }

    public string NOMBREBANCO { get; set; }

    public string DIRECCIONBANCO { get; set; }

    public string POBLACIONBANCO { get; set; }

    public string USUARIOCENTRALITA { get; set; }

    public int? VISIBILIDAD { get; set; }

    public int? IDHOTEL { get; set; }

    public string NEWPASSENTRADA { get; set; }

    public string NEWPASSREGISTRO { get; set; }

    public bool SUSCEPSUSTITUCION { get; set; }

    public string CODIGOIBAN { get; set; }

    public double? COSTEHORAEXTRA2 { get; set; }

    public string PASSWORDENTRADARFID { get; set; }

    public string PASSWORDREGISTRORFID { get; set; }

    public byte[] VERSION { get; set; }
}